/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AlitaFirst {
    /**
    * The name
    */
    'name': string;
  }
  interface AlitaFirstAttributes extends StencilHTMLAttributes {
    /**
    * The name
    */
    'name'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AlitaFirst': Components.AlitaFirst;
  }

  interface StencilIntrinsicElements {
    'alita-first': Components.AlitaFirstAttributes;
  }


  interface HTMLAlitaFirstElement extends Components.AlitaFirst, HTMLStencilElement {}
  var HTMLAlitaFirstElement: {
    prototype: HTMLAlitaFirstElement;
    new (): HTMLAlitaFirstElement;
  };

  interface HTMLElementTagNameMap {
    'alita-first': HTMLAlitaFirstElement
  }

  interface ElementTagNameMap {
    'alita-first': HTMLAlitaFirstElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
